[[headers]]
  for = "/Build/*.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/gzip"

[[headers]]
  for = "/*.js.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"

[build]
  publish = "."

[build.processing]
  skip_processing = true